services:
  - type: web
    name: gqtrack-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.11.9
    envVars:
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_zYiUDlx9guT4
      - key: DB_HOST
        value: ep-noisy-morning-acr135qf-pooler.sa-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: neondb
      - key: DB_SSL_MODE
        value: require
      - key: SECRET_KEY
        value: lucas_super_secreto_123
